name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: Please look at the [roadmap](https://github.com/Lordof21/OpenDex/blob/main/docs/ROADMAP.md) first.
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
      description: The problem, not the solution.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
      description: Your idea, and alternatives you considered.
  - type: dropdown
    id: help
    attributes:
      label: Would you like to work on it?
      options:
        - "Yes"
        - Maybe, with guidance
        - "No"
