// The sample world the mock backend answers from: an imaginary phone ("Example Phone") with fictional apps (com.example.*).
// Whatever the BACKEND CODE derives (settings defaults, windows, the battery report, the startup snapshot, notifications,
// the load insights, the per-app audio state) comes from sample-data.json, generated by gen_fixtures.py. What only the phone
// knows (volumes, toggles, Wi-Fi, Bluetooth, the media session) is written out here.
//
// Nothing in here is real: no device, account, network, track or person. Addresses are RFC 5737 documentation addresses.
const fs = require('fs');
const path = require('path');

const DATA = JSON.parse(fs.readFileSync(path.join(__dirname, 'sample-data.json'), 'utf8'));

/** A small generated cover (an SVG data URI): two soft colour fields and a ring — never a real album's artwork. */
function cover(hueA, hueB) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">`
    + `<stop offset="0" stop-color="hsl(${hueA} 80% 55%)"/><stop offset="1" stop-color="hsl(${hueB} 75% 38%)"/></linearGradient></defs>`
    + `<rect width="400" height="400" fill="url(#g)"/><circle cx="270" cy="150" r="120" fill="hsl(${hueB} 90% 70% / .35)"/>`
    + `<circle cx="200" cy="200" r="62" fill="none" stroke="rgba(255,255,255,.55)" stroke-width="10"/></svg>`;
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
}

/** An app icon: a rounded square in the app's colours with its first letter — drawn here, never a real app's logo. */
function appIcon(label, hueA, hueB) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="192" height="192" viewBox="0 0 192 192"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">`
    + `<stop offset="0" stop-color="hsl(${hueA} 78% 58%)"/><stop offset="1" stop-color="hsl(${hueB} 72% 42%)"/></linearGradient></defs>`
    + `<rect width="192" height="192" rx="44" fill="url(#g)"/><text x="96" y="124" font-family="system-ui, Arial, sans-serif" font-size="92" font-weight="700" `
    + `text-anchor="middle" fill="#fff" fill-opacity=".95">${label}</text></svg>`;
}

const ICON_HUES = {
  'com.example.clips': [350, 20], 'com.example.notes': [45, 30], 'com.example.chat': [150, 175], 'com.example.maps': [135, 200],
  'com.example.photos': [275, 320], 'com.example.tunes': [320, 280], 'com.example.mail': [210, 235], 'com.example.calendar': [8, 28],
  'com.example.camera': [220, 260], 'com.example.browser': [195, 215], 'com.example.clock': [255, 235], 'com.example.calc': [28, 12],
};

function iconFor(pkg) {
  const app = DATA.apps.find((a) => a.package === pkg);
  const hues = ICON_HUES[pkg];
  if (!app || !hues) return null;
  return appIcon(app.display_name[0], hues[0], hues[1]);
}

const SCENE_OF = { 'com.example.clips': 'clips', 'com.example.notes': 'notes', 'com.example.chat': 'chat', 'com.example.maps': 'maps', 'com.example.photos': 'photos' };

/** The clock-relative parts of the sample world, shifted to `nowSec` (the screenshot tool's own clock). */
function build(nowSec = Date.now() / 1000) {
  const load = JSON.parse(JSON.stringify(DATA.load));
  load.now = nowSec;
  load.samples.forEach((s) => { s.t = nowSec + s.t_offset; delete s.t_offset; });
  load.markers.forEach((m) => { m.t = nowSec + m.t_offset; delete m.t_offset; });

  const clock = (ageMin) => new Date((nowSec - ageMin * 60) * 1000).toLocaleTimeString('tr-TR', { hour: '2-digit', minute: '2-digit' });
  const notifications = JSON.parse(JSON.stringify(DATA.notifications)).map((n) => {
    n.timestamp = nowSec - n.age_min * 60;
    n.post_time = clock(n.age_min);
    delete n.age_min;
    return n;
  });

  return {
    ...JSON.parse(JSON.stringify(DATA)),
    load,
    notifications,
    health: { ok: true, version: '0.1.0', auth: 'bearer' },
    profile: { model: 'Example Phone', android_api: 15, width: 1080, height: 2400, density: 420, max_encoder_sessions: 6 },
    battery: {
      type: 'battery_update', ok: true, level: 84, scale: 100, status: 2, is_charging: true, charging_type: 'USB', health: 'GOOD',
      technology: 'Li-ion', temperature_c: 33.4, voltage_mv: 4310,
    },
    states: {
      ok: true, type: 'states_update', screen_on: true,
      states: { wifi: true, bluetooth: true, mobile_data: false, airplane_mode: false, rotation_lock: false, mute: false, torch: false, screen_on: true },
    },
    volumes: {
      ok: true, type: 'volumes_update',
      streams: [
        { id: 3, name: 'MUSIC', label: 'Medya', current: 11, max: 15, min: 0, muted: false },
        { id: 2, name: 'RING', label: 'Zil Sesi', current: 5, max: 7, min: 0, muted: false },
        { id: 5, name: 'NOTIFICATION', label: 'Bildirim', current: 5, max: 7, min: 0, muted: false },
        { id: 4, name: 'ALARM', label: 'Alarm', current: 6, max: 7, min: 1, muted: false },
      ],
    },
    displayPower: { ok: true, on: true },
    wifi: {
      status: {
        enabled: true, connected: true, ssid: 'Example-Home', rssi: -51, bars: 4, tx_mbps: 866, rx_mbps: 780, band: '5 GHz', frequency: 5180,
        standard: 'Wi-Fi 6', security: 'WPA3', ip: '192.0.2.45',
      },
      saved: [
        { network_id: 0, ssid: 'Example-Home', security: 'wpa3', kind: 'saved' },
        { network_id: 1, ssid: 'Example-Office', security: 'wpa2', kind: 'saved' },
      ],
    },
    networks: {
      networks: [
        { ssid: 'Example-Home', bssid: '02:00:00:00:00:01', frequency: 5180, band: '5 GHz', rssi: -51, bars: 4, secured: true, security: 'wpa3', connectable: true },
        { ssid: 'Example-Guest', bssid: '02:00:00:00:00:02', frequency: 2437, band: '2.4 GHz', rssi: -63, bars: 3, secured: false, security: 'open', connectable: true },
        { ssid: 'Example-Office', bssid: '02:00:00:00:00:03', frequency: 5240, band: '5 GHz', rssi: -72, bars: 2, secured: true, security: 'wpa2', connectable: true },
      ],
    },
    bluetooth: {
      ok: true, enabled: true, name: 'Example Phone', readonly: false, source: 'daemon',
      devices: [
        { address: '02:00:00:AA:BB:01', name: 'Example Buds', kind: 'headphones', connected: true, battery: 78 },
        { address: '02:00:00:AA:BB:02', name: 'Example Speaker', kind: 'speaker', connected: false, battery: null },
        { address: '02:00:00:AA:BB:03', name: 'Example Watch', kind: 'watch', connected: false, battery: null },
      ],
    },
    media: {
      type: 'media_update', active: true, seq: 1, epoch: 1, package: 'com.example.tunes', track_id: 'tunes::1', title: 'Slow Light', artist: 'Sample Ensemble',
      album: 'Daybreak Sessions', album_art: cover(330, 270), art_ready: true, state: 'PLAYING', is_playing: true, position: 74_000, duration: 212_000, speed: 1,
      sessions: [
        { package: 'com.example.tunes', track_id: 'tunes::1', title: 'Slow Light', artist: 'Sample Ensemble', album: 'Daybreak Sessions', album_art: cover(330, 270),
          art_ready: true, state: 'PLAYING', is_playing: true, position: 74_000, duration: 212_000, speed: 1 },
        { package: 'com.example.clips', track_id: 'clips::1', title: 'Northern lights, a month in 4 minutes', artist: 'Sample channel', album: '', album_art: cover(190, 150),
          art_ready: true, state: 'PAUSED', is_playing: false, position: 91_000, duration: 244_000, speed: 0 },
      ],
    },
    transfers: [],
    // GET /telemetry — what the Device Center shows (per-app CPU, per-window stream rate, the adb link).
    telemetry: {
      ts: nowSec, interval_s: 2.0,
      device: { cpu_pct: 26.4, cores: 8, adb_rtt_ms: 9.0, shell_routes: { daemon: 412, adb: 3 } },
      streams: {
        'win-clips': { fps: 59.6, mbps: 7.8, clients: 1 }, 'win-notes': { fps: 24.1, mbps: 1.1, clients: 1 }, 'win-chat': { fps: 12.0, mbps: 0.6, clients: 1 },
      },
      windows: {
        'win-clips': { stream_id: 'win-clips', package: 'com.example.clips', locus: 'desktop' },
        'win-notes': { stream_id: 'win-notes', package: 'com.example.notes', locus: 'desktop' },
        'win-chat': { stream_id: 'win-chat', package: 'com.example.chat', locus: 'desktop' },
      },
      apps: [
        { package: 'com.example.clips', locus: 'desktop', window_ids: ['win-clips'], cpu_pct: 8.9, processes: 2 },
        { package: 'com.example.notes', locus: 'desktop', window_ids: ['win-notes'], cpu_pct: 3.1, processes: 1 },
        { package: 'com.example.chat', locus: 'desktop', window_ids: ['win-chat'], cpu_pct: 1.4, processes: 1 },
        { package: 'com.example.tunes', locus: 'phone', window_ids: [], cpu_pct: 0.8, processes: 1 },
      ],
    },
  };
}

module.exports = { build, iconFor, SCENE_OF, cover };
