#!/usr/bin/env python3
"""Regenerates every GENERATED part of the documentation from the code, so the docs cannot drift from it.

    python scripts/docgen.py            # rewrite what is out of date
    python scripts/docgen.py --check    # change nothing; exit 1 when something is out of date (CI, tests/test_docs_generated.py)

What is generated (everything else under docs/ is written by hand):

  docs/api/openapi.json        the public OpenAPI 3.1 document          (backend/app/api/openapi_export.py)
  docs/api/REFERENCE.md        one section per operation of that document
  docs/API.md                  blocks between  <!-- BEGIN GENERATED: name --> … <!-- END GENERATED: name -->
                               (WebSocket routes, event types, /ws/input message types)
  docs/CONFIGURATION.md        every OPENDEX_* setting, from backend/app/config.py and its comments
  docs/DAEMON_PROTOCOL.md      blocks: the daemon's capabilities and commands, from the Java source
  THIRD_PARTY_NOTICES.md       the licences of what OpenDeX is built from

Only the backend is IMPORTED (no device, no network).
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))
sys.path.insert(0, str(ROOT / "scripts"))

BLOCK_RE = r"<!-- BEGIN GENERATED: {name} -->\n(.*?)<!-- END GENERATED: {name} -->"
HTTP_METHODS = ("get", "post", "put", "patch", "delete")
GENERATED_NOTE = "<!-- This file is GENERATED by scripts/docgen.py — do not edit; change the code and regenerate. -->"


# ============================================================================================ helpers


def splice(text: str, name: str, content: str) -> str:
    """Replaces the body of the named generated block in `text`."""
    pattern = re.compile(BLOCK_RE.format(name=re.escape(name)), re.DOTALL)
    if not pattern.search(text):
        raise SystemExit(f"generated block '{name}' not found — add the BEGIN/END markers to the document first")
    return pattern.sub(lambda _m: f"<!-- BEGIN GENERATED: {name} -->\n{content.rstrip()}\n<!-- END GENERATED: {name} -->", text, count=1)


def md_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def first_paragraph(doc: str | None) -> str:
    if not doc:
        return ""
    lines: list[str] = []
    for raw in doc.strip().splitlines():
        if not raw.strip():
            if lines:
                break
            continue
        lines.append(raw.strip())
    return " ".join(lines)


# ============================================================================================ OpenAPI reference


def _num(value: Any) -> Any:
    """`0.0` → `0`, `2.5` stays — a bound is shown the way a person would write it."""
    return int(value) if isinstance(value, float) and value.is_integer() else value


def _bounds(schema: dict[str, Any]) -> str:
    """` (0–100)`, ` (≥ 0)`, ` (≤ 65535)`, ` (> 0)` — empty when the number is unbounded."""
    low, high = _num(schema.get("minimum")), _num(schema.get("maximum"))
    above, below = _num(schema.get("exclusiveMinimum")), _num(schema.get("exclusiveMaximum"))
    if low is not None and high is not None:
        return f" ({low}–{high})"
    parts = []
    if low is not None:
        parts.append(f"≥ {low}")
    if above is not None:
        parts.append(f"> {above}")
    if high is not None:
        parts.append(f"≤ {high}")
    if below is not None:
        parts.append(f"< {below}")
    return f" ({', '.join(parts)})" if parts else ""


# What a shared response (components.responses) is called in the one-line "Responses:" list of every operation.
SHARED_LABELS = {"NoDevice": "no device bound", "Unauthorized": "token missing/wrong", "ForeignOrigin": "foreign Origin/Host",
                 "LengthRequired": "chunked body", "PayloadTooLarge": "body too large"}


class Resolver:
    def __init__(self, spec: dict[str, Any]) -> None:
        self.spec = spec

    def deref(self, schema: dict[str, Any]) -> dict[str, Any]:
        seen = 0
        while "$ref" in schema and seen < 10:
            node: Any = self.spec
            for part in schema["$ref"].lstrip("#/").split("/"):
                node = node[part]
            schema, seen = node, seen + 1
        return schema

    def type_of(self, schema: dict[str, Any], depth: int = 0) -> str:
        """A short human type: `integer (0–100)`, `string`, `"a" | "b"`, `array of string`, `object`, `Name`."""
        if "$ref" in schema:
            return f"`{schema['$ref'].rsplit('/', 1)[-1]}`"
        if "enum" in schema:
            return " \\| ".join(f"`{json.dumps(v, ensure_ascii=False)}`" for v in schema["enum"])
        if "const" in schema:
            return f"`{json.dumps(schema['const'], ensure_ascii=False)}`"
        for key in ("anyOf", "oneOf"):
            if key in schema:
                parts = [self.type_of(s, depth + 1) for s in schema[key]]
                nullable = "null" in parts
                parts = [p for p in parts if p != "null"]
                joined = " \\| ".join(dict.fromkeys(parts)) or "any"
                return f"{joined} (nullable)" if nullable else joined
        kind = schema.get("type")
        if kind == "array":
            return f"array of {self.type_of(schema.get('items', {}), depth + 1)}"
        if kind in ("integer", "number"):
            return f"{kind}{_bounds(schema)}"
        if kind == "string":
            extras = []
            if "minLength" in schema and "maxLength" in schema:
                extras.append(f"{schema['minLength']}–{schema['maxLength']} chars")
            elif "maxLength" in schema:
                extras.append(f"≤ {schema['maxLength']} chars")
            elif schema.get("minLength"):
                extras.append(f"≥ {schema['minLength']} chars")
            if "pattern" in schema:
                extras.append("pattern")
            if schema.get("format"):
                extras.append(schema["format"])
            return "string" + (f" ({', '.join(extras)})" if extras else "")
        if kind == "object" or "properties" in schema:
            return "object"
        return kind or "any"

    def fields(self, schema: dict[str, Any]) -> list[tuple[str, str, bool, str]]:
        """(name, type, required, note) for an object schema; empty when it is not one."""
        schema = self.deref(schema)
        props = schema.get("properties") or {}
        required = set(schema.get("required") or [])
        rows = []
        for name, prop in props.items():
            note_parts = []
            if "default" in prop:
                note_parts.append(f"default `{json.dumps(prop['default'], ensure_ascii=False)}`")
            if prop.get("description"):
                note_parts.append(prop["description"])
            rows.append((name, self.type_of(prop), name in required, "; ".join(note_parts)))
        return rows


def render_reference(spec: dict[str, Any]) -> str:
    res = Resolver(spec)
    tag_order = [t["name"] for t in spec.get("tags", [])]
    by_tag: dict[str, list[tuple[str, str, dict[str, Any]]]] = {}
    for path, ops in spec["paths"].items():
        for method in HTTP_METHODS:
            if method in ops:
                tag = (ops[method].get("tags") or ["general"])[0]
                by_tag.setdefault(tag, []).append((method, path, ops[method]))
    ordered = [t for t in ["general", *tag_order] if t in by_tag] + [t for t in by_tag if t not in tag_order and t != "general"]
    tag_desc = {t["name"]: t["description"] for t in spec.get("tags", [])}
    tag_desc["general"] = "Liveness and the opt-in token handout."
    total = sum(len(v) for v in by_tag.values())

    out = [GENERATED_NOTE, "", "# API reference", "",
           f"All {total} operations of the public OpenAPI document ([`openapi.json`](openapi.json), OpenAPI {spec['openapi']}), grouped by tag. "
           "Conventions that apply to every operation — authentication, the Origin/Host guard, limits, error shapes — are in "
           "[API.md](../API.md); the WebSocket channels and the event types are there too.", "",
           "Paths are relative to `http://127.0.0.1:8710/api/v1` (every operation is also served under `/api`, unversioned). "
           "**Auth** `token` = needs the API token; **Device** = answers `409` while no phone is bound.", "",
           "| Group | Operations |", "|---|---|"]
    for tag in ordered:
        out.append(f"| [{tag}](#{tag}) | {len(by_tag[tag])} |")
    out.append("")
    out += ["The same few refusals apply to many operations; they are named once here and abbreviated in each operation's "
            "*Responses* line:", "", "| Status | Short name | Meaning |", "|---|---|---|"]
    shared_status = {"NoDevice": "409", "Unauthorized": "401", "ForeignOrigin": "403", "LengthRequired": "411", "PayloadTooLarge": "413"}
    for name, status in sorted(shared_status.items(), key=lambda kv: kv[1]):
        out.append(f"| `{status}` | {SHARED_LABELS[name]} | {md_escape(spec['components']['responses'][name]['description'])} |")
    out.append("")

    for tag in ordered:
        out += [f"## {tag}", "", tag_desc.get(tag, ""), "",
                "| Method | Path | Summary | Auth | Device |", "|---|---|---|---|---|"]
        for method, path, op in by_tag[tag]:
            short = path[len("/api/v1"):]
            summary = md_escape(first_paragraph(op.get("description")) or op.get("summary", ""))
            if len(summary) > 110:
                summary = summary[:107].rstrip() + "…"
            token = "—" if op.get("security") == [] else "token"
            out.append(f"| `{method.upper()}` | `{short}` | {summary} | {token} | {'yes' if op.get('x-requires-device') else ''} |")
        out.append("")
        for method, path, op in by_tag[tag]:
            short = path[len("/api/v1"):]
            out += [f"### `{method.upper()} {short}`", ""]
            desc = (op.get("description") or "").strip()
            out += [desc if desc else (op.get("summary") or ""), ""]
            flags = []
            flags.append("no token" if op.get("security") == [] else "token required")
            if op.get("x-requires-device"):
                flags.append("needs a bound device (`409` otherwise)")
            out += [f"*{'; '.join(flags)}*", ""]

            params = op.get("parameters") or []
            if params:
                out += ["| Parameter | In | Type | Required | Notes |", "|---|---|---|---|---|"]
                for p in params:
                    notes = []
                    schema = p.get("schema", {})
                    if "default" in schema:
                        notes.append(f"default `{json.dumps(schema['default'], ensure_ascii=False)}`")
                    if p.get("description"):
                        notes.append(p["description"])
                    out.append(f"| `{p['name']}` | {p['in']} | {res.type_of(schema)} | {'yes' if p.get('required') else 'no'} | {md_escape('; '.join(notes))} |")
                out.append("")

            body = (op.get("requestBody") or {}).get("content", {})
            if body:
                ctype, content = next(iter(body.items()))
                schema = content.get("schema", {})
                rows = res.fields(schema)
                label = {"application/json": "JSON"}.get(ctype, ctype)
                name = schema.get("$ref", "").rsplit("/", 1)[-1]
                out.append(f"**Request body** ({label}{f', `{name}`' if name else ''}){'' if rows else ' — not schematized'}")
                out.append("")
                if rows:
                    out += ["| Field | Type | Required | Notes |", "|---|---|---|---|"]
                    for fname, ftype, req, note in rows:
                        out.append(f"| `{fname}` | {ftype} | {'yes' if req else 'no'} | {md_escape(note)} |")
                    out.append("")

            codes = []
            for code, resp in (op.get("responses") or {}).items():
                if "$ref" in resp:
                    shared = resp["$ref"].rsplit("/", 1)[-1]
                    resp_desc = SHARED_LABELS.get(shared) or spec["components"]["responses"][shared]["description"]
                else:
                    resp_desc = resp.get("description", "")
                codes.append(f"`{code}` {md_escape(resp_desc).split('. ')[0].rstrip('.')}")
            out += ["**Responses:** " + " · ".join(codes), ""]
    return "\n".join(out).rstrip() + "\n"


# ============================================================================================ API.md blocks


def ws_routes_block() -> str:
    from app.api.websockets import INPUT_MESSAGE_TYPES, ws_router  # noqa: F401

    rows = ["| Channel | Direction | Purpose |", "|---|---|---|"]
    direction = {"/ws/video/{window_id}": "server → client (binary); client → server `keyframe`",
                 "/ws/audio": "server → client (binary)", "/ws/audio/{window_id}": "server → client (binary)",
                 "/ws/input/{window_id}": "client → server (JSON)", "/ws/events": "server → client (JSON); client → server (JSON commands)"}
    for route in ws_router.routes:
        doc = first_paragraph(route.endpoint.__doc__)
        rows.append(f"| `{route.path}` | {direction.get(route.path, '')} | {md_escape(doc)} |")
    return "\n".join(rows)


def input_types_block() -> str:
    from app.api.websockets import INPUT_MESSAGE_TYPES

    return ", ".join(f"`{t}`" for t in sorted(INPUT_MESSAGE_TYPES))


def events_block() -> str:
    """The EventType literal of backend/app/events.py with its trailing comments (the payload sketches)."""
    source = (ROOT / "backend" / "app" / "events.py").read_text(encoding="utf-8")
    start = source.index("EventType = Literal[")
    end = source.index("\n]\n", start)
    rows = ["| Event `type` | Payload |", "|---|---|"]
    group = ""
    for line in source[start:end].splitlines()[1:]:
        stripped = line.strip()
        header = re.match(r"#\s*---\s*(.+?)\s*---", stripped)
        if header:
            group = md_escape(re.sub(r"\(.*?\)", "", header.group(1))).strip()
            rows.append(f"| **{group}** | |")
            continue
        m = re.match(r'"([a-z_0-9]+)",\s*(?:#\s*(.*))?$', stripped)
        if m:
            rows.append(f"| `{m.group(1)}` | {md_escape(m.group(2) or '')} |")
    return "\n".join(rows)


# ============================================================================================ configuration reference


def render_configuration() -> str:
    """docs/CONFIGURATION.md: every OPENDEX_* setting with its type, default and the comment written above it."""
    source_path = ROOT / "backend" / "app" / "config.py"
    source = source_path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    settings_cls = next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == "Settings")
    lines = source.splitlines()

    from app.config import Settings

    fields = Settings.model_fields
    rows: list[tuple[str, str, str, str, str]] = []          # (section, NAME, type, default, comment)
    section = "General"
    for node in settings_cls.body:
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        name = node.target.id
        if name not in fields:
            continue
        # the comment block directly above the field (and `# --- Section ---` markers above that)
        comment: list[str] = []
        i = node.lineno - 2
        while i >= 0 and lines[i].strip().startswith("#"):
            comment.insert(0, lines[i].strip().lstrip("#").strip())
            i -= 1
        # a `# --- Section ---` line is a section marker, not part of the comment
        cleaned = []
        for text in comment:
            m = re.match(r"-+\s*(.+?)\s*-+$", text)
            if m:
                section = re.sub(r"\s*\(.*?\)\s*", " ", m.group(1)).strip()
            else:
                cleaned.append(text)
        trailing = ""
        end_line = lines[node.end_lineno - 1] if node.end_lineno else ""
        if "#" in end_line.split("=", 1)[-1] and node.lineno == node.end_lineno:
            trailing = end_line.rsplit("#", 1)[-1].strip()
        info = fields[name]
        annotation = ast.unparse(node.annotation)
        default = _default_text(info)
        rows.append((section, name, annotation, default, " ".join(cleaned + ([trailing] if trailing else [])).strip()))

    out = [GENERATED_NOTE, "", "# Configuration reference", "",
           "Every tunable of the backend is an environment variable with the prefix `OPENDEX_` (a `.env` file next to where the backend "
           "starts is read too). Nothing is hard-coded at call sites. Values are validated at start-up; an invalid value stops the "
           "backend with a message instead of running half-configured.", "",
           f"{len(rows)} settings, generated from [`backend/app/config.py`](../backend/app/config.py) — the comment above each setting "
           "there is the description below.", ""]
    current = None
    for sec, name, typ, default, comment in rows:
        if sec != current:
            out += ["", f"## {sec}", "", "| Variable | Type | Default | Description |", "|---|---|---|---|"]
            current = sec
        out.append(f"| `OPENDEX_{name}` | `{md_escape(typ)}` | {default} | {md_escape(comment)} |")
    return "\n".join(out).rstrip() + "\n"


def _default_text(info: Any) -> str:
    from pydantic_core import PydanticUndefined

    if info.default_factory is not None:
        try:
            value = info.default_factory()
        except Exception:  # noqa: BLE001
            return "*(computed)*"
        return _fmt_default(value)
    if info.default is PydanticUndefined:
        return "*(required)*"
    return _fmt_default(info.default)


def _fmt_default(value: Any) -> str:
    if value is None:
        return "*(unset)*"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, (list, tuple, set)):
        text = json.dumps([str(v) for v in value], ensure_ascii=False)
        return f"`{text}`" if len(text) < 80 else f"*({len(value)} entries)*"
    text = str(value)
    home = str(Path.home())
    text = text.replace(home, "~")                          # the generating machine's home must not leak into the docs
    return f"`{text}`" if text else "`\"\"`"


# ============================================================================================ daemon protocol blocks


DAEMON_SRC = ROOT / "backend" / "java" / "src" / "com" / "opendex" / "tools"


def daemon_facts() -> dict[str, list[str]]:
    """What the daemon's Java source declares: the capability list (base, and the extras a token adds), the commands of
    its main dispatch, and the `fs_*` commands of FsWire."""
    source = (DAEMON_SRC / "OpenDexDaemon.java").read_text(encoding="utf-8")

    caps_body = re.search(r"CAPABILITIES = Arrays\.asList\((.*?)\n    \);", source, re.DOTALL).group(1)
    caps_body = re.sub(r"//[^\n]*", "", caps_body)                       # line comments hold quotes and parentheses
    base = re.findall(r'"([a-z_0-9]+)"', caps_body)
    with_token = re.findall(r'caps\.add\("([a-z_0-9]+)"\)', source)

    dispatch = source[source.index("private static JSONObject handleCommand"):]
    dispatch = dispatch[: dispatch.index('default: return res.put("type", "error")')]
    commands = list(dict.fromkeys(re.findall(r'case "([a-z_0-9]+)"', dispatch)))

    wire = (DAEMON_SRC / "FsWire.java").read_text(encoding="utf-8")
    parse = wire[wire.index("static Request parse"):]
    parse = parse[: parse.index("default:")]
    fs_commands = list(dict.fromkeys(re.findall(r'case "(fs_[a-z_0-9]+)"', parse)))
    return {"capabilities": base, "capabilities_token": with_token, "commands": commands, "fs_commands": fs_commands}


def daemon_blocks() -> dict[str, str]:
    facts = daemon_facts()

    def codes(names: list[str]) -> str:
        return ", ".join(f"`{n}`" for n in names)

    return {
        "capabilities": codes(facts["capabilities"]),
        "capabilities-token": codes(facts["capabilities_token"]),
        "commands": codes(facts["commands"]),
        "fs-commands": codes(facts["fs_commands"]),
    }


# ============================================================================================ orchestration


def desired_files() -> dict[Path, str]:
    """Every generated file's full new content, keyed by path."""
    import export_openapi

    files: dict[Path, str] = {}
    openapi_text = export_openapi.render()
    files[ROOT / "docs" / "api" / "openapi.json"] = openapi_text
    files[ROOT / "docs" / "api" / "REFERENCE.md"] = render_reference(json.loads(openapi_text))
    files[ROOT / "docs" / "CONFIGURATION.md"] = render_configuration()

    api_md = ROOT / "docs" / "API.md"
    if api_md.exists():
        text = api_md.read_text(encoding="utf-8")
        for name, content in (("ws-routes", ws_routes_block()), ("ws-input-types", input_types_block()), ("events", events_block())):
            if f"<!-- BEGIN GENERATED: {name} -->" in text:
                text = splice(text, name, content)
        files[api_md] = text

    daemon_md = ROOT / "docs" / "DAEMON_PROTOCOL.md"
    if daemon_md.exists():
        text = daemon_md.read_text(encoding="utf-8")
        for name, content in daemon_blocks().items():
            if f"<!-- BEGIN GENERATED: {name} -->" in text:
                text = splice(text, name, content)
        files[daemon_md] = text

    notices = ROOT / "scripts" / "third_party_notices.py"
    if notices.exists():
        import third_party_notices

        files[ROOT / "THIRD_PARTY_NOTICES.md"] = third_party_notices.render()
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="do not write; exit 1 when a generated file is out of date")
    args = parser.parse_args()

    stale: list[Path] = []
    for path, content in desired_files().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if args.check:
        for path in stale:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        if stale:
            print("run: python scripts/docgen.py", file=sys.stderr)
        return 1 if stale else 0
    if not stale:
        print("generated documentation is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
