"""The PUBLIC OpenAPI document of the OpenDeX backend (docs/api/openapi.json).

FastAPI already derives a schema from the routes (``app.openapi()``); this module turns it into something a third party
can build a client against:

  * only the versioned ``/api/v1/*`` surface — every route is also served unversioned under ``/api/*`` (the bundled UI
    uses that alias and it always tracks the latest version); one copy of each operation is enough in the document,
  * the rules that are NOT visible in the routes because middleware enforces them: bearer-token authentication
    (api/auth.py), the browser Origin/Host guard (api/origin_guard.py), the body limit and the security headers
    (api/hardening.py) — as security schemes and shared error responses,
  * descriptions for the tag groups.

``app.openapi()`` itself is left alone: tests/test_route_manifest.py pins the frontend contract on it.
The document is regenerated by ``python scripts/export_openapi.py`` and kept honest by tests/test_openapi_snapshot.py.
"""
from __future__ import annotations

import copy
from typing import Any

from fastapi import APIRouter, FastAPI
from fastapi.routing import APIRoute

from .deps import get_active_serial
from .v1.endpoints import apps, audio, devices, diagnostics, fs, input, notifications, pairing, settings, telemetry, windows

# The endpoint routers api/v1/router.py mounts. Their `routes` are plain APIRoute objects whatever the FastAPI version
# (the mounted app's own route list is a tree of lazily included routers on recent versions) — so the per-route facts the
# schema cannot show (the bound-device guard) are read from these. tests/test_openapi_snapshot.py pins that the list is complete.
ENDPOINT_ROUTERS: tuple[APIRouter, ...] = tuple(
    module.router for module in (devices, pairing, apps, windows, settings, audio, input, notifications, diagnostics, telemetry, fs)
)

PUBLIC_PREFIX = "/api/v1"
REPOSITORY_URL = "https://github.com/Lordof21/OpenDex"
DEFAULT_SERVER = "http://127.0.0.1:8710"

# Served without a token (api/auth.py EXEMPT_PATHS): liveness for the boot splash / Docker, and the opt-in token handout.
PUBLIC_OPERATIONS = frozenset({f"{PUBLIC_PREFIX}/health", f"{PUBLIC_PREFIX}/auth/bootstrap"})
_BODY_METHODS = frozenset({"post", "put", "patch"})
_HTTP_METHODS = frozenset({"get", "post", "put", "patch", "delete"})

DESCRIPTION = f"""\
The local control API of the **OpenDeX backend** — the process that drives an Android phone over `adb` and the patched
scrcpy server, and that the desktop UI talks to. It listens on `127.0.0.1:8710` by default.

### Authentication
Every `/api/*` request and every `/ws/*` handshake must present the API token — one secret per user, read from
`OPENDEX_API_TOKEN` or the file `~/.opendex/api-token` (created with mode 0600 on first start):

* `Authorization: Bearer <token>` (preferred), or
* a `token` query parameter — **only** on `GET` requests and WebSocket handshakes (browsers cannot set headers on those).

A missing/wrong token is `401` (HTTP) or WebSocket close code `4401`, before any route runs. Only `GET /health` and, when
`OPENDEX_TOKEN_BOOTSTRAP` is enabled, `GET /auth/bootstrap` are exempt.

### Browser protection
A request that carries an `Origin` header that is not one of the app's own origins is refused with `403` (WebSocket: close
code `4403`); so is a `Host` header that is not a loopback / `*.localhost` name (DNS rebinding). Clients without an `Origin`
header (curl, scripts) are not affected — they still need the token.

### Limits
Request bodies are capped (`OPENDEX_MAX_BODY_BYTES`, default 2 MB): `413` when the declared `Content-Length` is larger, `411` when a
body is sent chunked without a `Content-Length`, `400` when the declared length is not a number. Responses are never cached (`Cache-Control: no-store`).

### Versioning
`/api/v1/*` is the versioned surface. The same operations are also served unversioned as `/api/*` (an alias that tracks the
latest version — what the bundled UI calls). Breaking changes will get a new version prefix.

### Not described here
Real-time channels are WebSockets, which OpenAPI cannot describe: `/ws/events` (JSON events), `/ws/video/{{window_id}}`,
`/ws/audio`, `/ws/audio/{{window_id}}` (binary media) and `/ws/input/{{window_id}}` (JSON touch/keyboard messages). They are
specified in [docs/API.md]({REPOSITORY_URL}/blob/main/docs/API.md).
"""

TAGS: list[dict[str, str]] = [
    {"name": "devices", "description": "The bound phone: connection state, battery and its diagnostics, volumes, quick toggles "
     "(Wi-Fi, Bluetooth, mobile data …), screen power, Wi-Fi/Bluetooth management, startup progress."},
    {"name": "pairing", "description": "Wireless debugging: QR pairing, mDNS discovery, connect by IP."},
    {"name": "apps", "description": "Installed apps of the phone (list, icons) and launching them."},
    {"name": "windows", "description": "Mirror windows: one phone app per virtual display — open, close, resize, density, "
     "Workspace (freeform) tasks, hand-off to the phone, video/keyframe control."},
    {"name": "settings", "description": "Project settings (persisted) and window layouts."},
    {"name": "audio", "description": "Per-app audio routing (Phone / DeX / Both), the cross-device sync and its calibration."},
    {"name": "input", "description": "Keyboard and key injection (touch and pointer input travel over the `/ws/input/{window_id}` WebSocket)."},
    {"name": "notifications", "description": "The phone's notifications (list, act, dismiss, open) and media-session control."},
    {"name": "diagnostics", "description": "Environment and capability checks, logs, encoder tests."},
    {"name": "telemetry", "description": "Phone load: CPU/thermal/power attribution, per-window stream rates, what OpenDeX itself sends to the phone."},
    {"name": "fs", "description": "File manager over the PC and the phone: browse, transfer, preview, trash, properties."},
]

RESPONSES: dict[str, dict[str, Any]] = {
    "NoDevice": {
        "description": "No phone is bound to the backend right now (`detail` is the text \"Cihaz bağlı değil.\"). The operation "
                       "needs a connected device; poll `GET /devices/state` or listen for the `device_connected` event.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorDetail"}}},
    },
    "Unauthorized": {
        "description": "The API token is missing or wrong (WebSocket: close code 4401).",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorDetail"}}},
    },
    "ForeignOrigin": {
        "description": "The request carries an `Origin` that is not one of the app's own origins, or a `Host` that is not a "
                       "loopback name (WebSocket: close code 4403).",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorDetail"}}},
    },
    "LengthRequired": {
        "description": "The request body was sent with chunked transfer-encoding and no `Content-Length` (chunked bodies are refused).",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorDetail"}}},
    },
    "PayloadTooLarge": {
        "description": "The request body is larger than `OPENDEX_MAX_BODY_BYTES` (default 2 MB).",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorDetail"}}},
    },
}

SECURITY_SCHEMES: dict[str, dict[str, Any]] = {
    "bearerAuth": {
        "type": "http", "scheme": "bearer",
        "description": "The per-user API token (`OPENDEX_API_TOKEN` or `~/.opendex/api-token`).",
    },
    "tokenQuery": {
        "type": "apiKey", "in": "query", "name": "token",
        "description": "The same token as a query parameter — accepted on GET requests and WebSocket handshakes only.",
    },
}

ERROR_DETAIL_SCHEMA: dict[str, Any] = {
    "title": "ErrorDetail",
    "type": "object",
    "properties": {"detail": {"anyOf": [{"type": "string"}, {"type": "array"}, {"type": "object"}],
                              "description": "A human-readable message, a machine code (e.g. `not_supported`), or — for 422 — "
                                             "the list of validation errors."}},
    "required": ["detail"],
}


def _needs_device(route: APIRoute) -> bool:
    """True when the route (or the router it came from) depends on the bound-device guard (api/deps.py)."""
    stack = list(route.dependant.dependencies)
    while stack:
        dep = stack.pop()
        if dep.call is get_active_serial:
            return True
        stack.extend(dep.dependencies)
    return False


def public_schema(app: FastAPI) -> dict[str, Any]:
    """The documented API: `/api/v1/*` only, enriched with the rules the middleware enforces."""
    spec = copy.deepcopy(app.openapi())

    spec["info"] = {
        "title": "OpenDeX Backend API",
        "version": spec["info"]["version"],
        "summary": "Local control API of the OpenDeX backend (Android multi-window mirroring).",
        "description": DESCRIPTION,
        "license": {"name": "GPL-3.0-or-later", "identifier": "GPL-3.0-or-later"},   # OpenAPI 3.1: identifier XOR url
        "contact": {"name": "OpenDeX on GitHub", "url": REPOSITORY_URL},
    }
    spec["servers"] = [{"url": DEFAULT_SERVER, "description": "Default local listener (OPENDEX_HTTP_HOST / OPENDEX_HTTP_PORT)"}]
    spec["externalDocs"] = {"description": "Conventions, WebSocket protocols and events", "url": f"{REPOSITORY_URL}/blob/main/docs/API.md"}
    spec["tags"] = copy.deepcopy(TAGS)
    spec["security"] = [{"bearerAuth": []}, {"tokenQuery": []}]

    needs_device = {
        (f"{PUBLIC_PREFIX}{route.path}", method.lower())
        for router in ENDPOINT_ROUTERS for route in router.routes if isinstance(route, APIRoute) and _needs_device(route)
        for method in route.methods or ()
    }
    spec["paths"] = {path: ops for path, ops in spec["paths"].items() if path.startswith(f"{PUBLIC_PREFIX}/")}
    for path, ops in spec["paths"].items():
        for method, operation in ops.items():
            if method not in _HTTP_METHODS:
                continue
            responses = operation.setdefault("responses", {})
            if (path, method) in needs_device:
                operation["x-requires-device"] = True
                responses.setdefault("409", {"$ref": "#/components/responses/NoDevice"})
            if path in PUBLIC_OPERATIONS:
                operation["security"] = []
                if path.endswith("/bootstrap"):
                    operation["description"] = (operation.get("description") or "").strip() or (
                        "Hands the API token to a browser page from one of the app's own origins. Disabled unless "
                        "`OPENDEX_TOKEN_BOOTSTRAP=true` (the Docker/nginx deployment); the desktop build leaves it off. "
                        "An `Origin` header is required — non-browser clients read the token file instead."
                    )
                responses.setdefault("403", {"$ref": "#/components/responses/ForeignOrigin"})
                continue
            responses.setdefault("401", {"$ref": "#/components/responses/Unauthorized"})
            responses.setdefault("403", {"$ref": "#/components/responses/ForeignOrigin"})
            if method in _BODY_METHODS:
                responses.setdefault("411", {"$ref": "#/components/responses/LengthRequired"})
                responses.setdefault("413", {"$ref": "#/components/responses/PayloadTooLarge"})

    components = spec.setdefault("components", {})
    components["securitySchemes"] = copy.deepcopy(SECURITY_SCHEMES)
    components["responses"] = copy.deepcopy(RESPONSES)
    components.setdefault("schemas", {})["ErrorDetail"] = copy.deepcopy(ERROR_DETAIL_SCHEMA)
    components["schemas"] = dict(sorted(components["schemas"].items()))
    return spec
